### ISSUE TITLE
oCap MVP: Settings Page

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#115]
Users will be able to see, edit, and remove past permissions they've granted to dapps.

In the MVP, these permissions are limited to network switching and account access. These options will expand as future versions of this feature ship.

This is part of oCap MVP and relates to https://github.com/MetaMask/Design/issues/58

**Comment by cjeria** [comment]
I created a rough prototype of the address book in settings back when we first ideated on how it could work. Adding gif for feedback. cc @omnat @danjm @danfinlay @omnat 

You can play with it on Figma [here](https://www.figma.com/proto/giaffk6qfl9eMMjoPFjJkGnt/Address-book?node-id=7%3A291&viewport=430%2C199%2C0.08752364665269852&scaling=min-zoom) 
![address book in settings](http://g.recordit.co/kme8GaG0Vn.gif)

**Comment by danfinlay** [comment]
I think address book is a big enough deal to deserve more primary real-estate than "settings". I would put it in the tab bar along with tokens, history, subscriptions, etc.

**Comment by omnat** [comment]
@cjeria Is your proposal to manage permissions per account from within the 'My accounts' section of Address book settings?

I wonder if it could be too buried it the settings - for a bigger focus feature (moving forward atleast). Might be useful to do card sorting exercise with people if we are re-grouping and modifying info heirarchy to move away from global accounts.. Also a design jam might be nice to more effectively brainstorm :)

**Comment by omnat** [comment]
Sharing some low-fi concept explorations here, so we can maybe build upon / discuss different design directions

### Permissions manager concept

<img width="1166" alt="Screen Shot 2019-07-12 at 5 53 37 PM" src="https://user-images.githubusercontent.com/44038140/61164847-096f0600-a4ce-11e9-8202-f7676ae80fca.png">
Modify here: https://whimsical.com/R3MpU2jifUGNuAPzLueD5F


### On navigational (re)structure for global -> login per site

<img width="427" alt="Screen Shot 2019-07-12 at 6 04 11 PM" src="https://user-images.githubusercontent.com/44038140/61164980-7d5dde00-a4cf-11e9-8fcc-6280497e98bb.png">

### On Settings / options re-structure

<img width="693" alt="Screen Shot 2019-07-12 at 6 05 47 PM" src="https://user-images.githubusercontent.com/44038140/61164994-b39b5d80-a4cf-11e9-9b06-752fa84a4b0f.png">

Modify here: https://whimsical.com/R1Qsdg8WWiuoK7kocunaN

**Disclaimer: All these are just rough concept explorations, and un-tested!**

**Comment by cjeria** [comment]
@omnat I really like these concepts! I agree we should start by conducting a card sorting exercise before we get attached to any one idea.

Also, since it's a big change, I suggest we do a lot of experimentation with navigation.

After the card sorting exercise, we should:

- lo-fi wireframe / prototype
- usability test
- iterate

Repeat the above process as many times as necessary until we land on the best possible solution!

With regards to the focus of this issue - **permissions** are typically found inside of settings in all kinds of software and hardware products we use today. Browser permissions, laptop permissions, iPhone permissions are all found inside of a settings/system preferences section. We should build on existing mental models users have today. With card sorting, user testing and iterating, I belive we can get to an elegant and intuitive solution!

There are currently 2 options being discussed:

- Permissions in global wallet settings
- Permissions next to tokens & activity (top-level)

Other ideas
- Permissions in the account detail section. This is moving towards account-specific info/settings/permissions mental modal (as opposed to placing account-specific details inside of the global wallet settings area).

My current mental model of our product and the way it's architected is: 

* Wallet (global)
  * Settings
    * Security / Seed phrase
    * Networks
    * Advanced
    * Etc
  * Account(s)
    * Account details/settings
      * Priv/Pub Keys
      * Account name
      * Permissions (NEW)
      * etc
    * Account balance
    * Account history

Is the above structure understood by our users?  How can we make it more intuitive? What other ideas/options should we explore?

**Comment by danfinlay** [comment]
Laying out the app hierarchy is a really great exercise @cjeria, I couldn't help myself but take a swing at [how I think we could structure things](https://workflowy.com/s/app-hierarchy/7ya8ZIDuaOuxQclR) (re-pasted here, but that link will be more up to date):

### App hierarchy

- Wallet (global)
- Settings
  - Advanced:
    - Fields we show: Hex data, nonce field, etc.
    - Custom network RPC addresses
  - Etc
  - Extensions/plugins/modules (need a name that apple won't ban)
    - Types
      - Networks
      - Accounts
      - Asset types
    - Config screen
    - Permissions
    - Delete
- Accounts
  - Account type
    - Key-based accounts
      - Security / Seed phrase
        - Account(s)
      - Hardware wallets
      - Eventual remote signers (Trustology)
    - Other account types
      - Contract accounts
      - Saved passwords?
  - Account balance
  - Account history
  - Apps / Friends
    - Connected network
    - Granted permissions
  - Assets
    - Tokens
    - Collectibles
    - Subscriptions
    - "Powers"? (permissions granted to me)

**Comment by omnat** [comment]
Good plan, @cjeria! And @danfinlay your and CJ's app hierarchy listing here helped me create the cards of the card sorting study we should setup.

**Purpose of this study** is to understand mental models of people - which help us define what's an intuitive info hierarchy.
**Details of the study**: This will be moderated for 1st 5 participants; meaning, I'll be hearing them think out loud as they sort and group and organize different cards. Next 10-15 participants will do this unmoderated; meaning, remotely, using this link.

https://w682658s.optimalworkshop.com/optimalsort/metamask-0-0
Please use this link to access the study, and try to go through it as a participant. Even though none of us are eligible participants as we think way too much about info hierarchy and are opinionated because we work on it :D But I am certain you can help improve the study (especially the cards), please give feedback @cjeria @rachelcope @danfinlay :)

**Comment by omnat** [comment]
Check comments for #114

**Comment by rachelcope** [comment]
Expanded View
- [ ] Add Connected Sites link
- [ ] Design Connected Sites popup 
@rachelcope

**Comment by omnat** [comment]
Next step (week of Sept 30)
- [ ] Schedule call with dev for hand-off @rachelcope

**Comment by rachelcope** [comment]
Ready for development: 

https://www.figma.com/file/CvD7nhQVeSEB1QuSy3XhtY/oCap-Testing-Flow?node-id=535%3A2

**Comment by omnat** [comment]
Handed off to development! Will create new issue for QA when PR ready.
