### ISSUE TITLE
copy address button

### ISSUE THREAD

**Issue by jrmoreau** [MetaMask/Design#7]
"Really, really need "copy address" as a single click from the first menu -- almost the first thing you see. It's the thing I use the most, honestly. Having to click two things to get there = bad."

**Comment by cjeria** [comment]
@jrmoreau can you add the direct link to the support ticket?

**Comment by cjeria** [comment]
Filing this under design feedback.

**Comment by jrmoreau** [comment]
@cjeria is this repo private? If not I'd prefer to not. Instead I could link the github issue in the ticket and tag you.

**Comment by cjeria** [comment]
Latest copy to clipboard interaction
![copy to clipboard](https://user-images.githubusercontent.com/597770/40089937-6f8dcd76-5863-11e8-8b6d-c9230efaa756.gif)

**Comment by cjeria** [comment]
This design also referenced in issue addresses the copy address and open in etherscan accessibility problems https://github.com/MetaMask/metamask-extension/issues/3463

![account switching interaction concept2](https://user-images.githubusercontent.com/597770/39148316-dc0fbfba-46f0-11e8-8351-9dddd9517c38.gif)

**Comment by danfinlay** [comment]
That looks really nice.

As a user who is used to highlighting text to copy it, I would be tempted to make the address selectable text. This would raise the question: "How do you log into a different account?".

That's an especially important question since we're approaching a time when we support being logged into multiple sites at once, and so this pop-over view might only reflect the current tab's account. It might be useful to look at this design with that context, and maybe add the visual indication of the current site to this selector view.

**Comment by cjeria** [comment]
closing out as feature has been solved here https://github.com/MetaMask/metamask-extension/pull/4445#issuecomment-394422401
