### ISSUE TITLE
Payment Channels

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#86]
### Description
A feature that allows users to make transact free and instant transactions with select dApps (that support connext payment channel), after a 1st (with gas) setup

### Feature brief 
Per discussion with mobile team here https://docs.google.com/document/d/1NReZQ29WWcxbwpGygWmT0jFudI7CuU6u13S07oBW7Go/edit#

### Scope
Hoping to bump this up for public release - high impact, competitive edge, feasible solution

**Comment by bdresser** [comment]
Q: payment channel is related to a specific account?
A: yes it's a child / extension of one account

Q: if i have a payment channel and send to a dapp that hasn't set up a payment channel, do i lose funds? what about if I send to another person who hasn't set up the payment channel?
A: shouldn't get in to this position with a dapp - how would the user get the dapp's address? for a person, it just takes the receiver to "activate" the channel and decide to withdraw. So user A sends to a contract, and it stays in that contract until user B claims it.

**Comment by cjeria** [comment]
Here's the first pass at a wireframe of the `wallet` to `wallet` payment channel use case. These wires are building on @brunobar79 's POC video https://consensys.slack.com/archives/GBHSSFEN5/p1551827395051900

It's divided into three sub-flows:
1 - Deposit flow
2 - Send DAI flow
3 - Withdraw flow

Link to the figma for commenting.
https://www.figma.com/file/K1a0m5VRohRZV6EcpNzL6qxr/Payment-Channels?node-id=0%3A1
@brunobar79  @omnat @bdresser @danfinlay 

Questions that have come up:
- From the POC, when you deposit ETH into the payment channel, it's automatically swaps it to DAI. Should the user have the option to use ETH as well?
- Can we display a reciept in the tx history when depositing funds into the payment channel?
- In the send flow, should we include the address book into the flow?
- Is there a network fee when withdrawing from the payment channel?
- - Can the user withdraw a % of their payment channel funds or are users required to withdraw 100% of the funds in order to "close" the payment channel?
- When thinking about State Channels, will users be able to use this Payment Channel for interactions with Dapps or is it required to open new State Channels (new containers that holds ETH/DAI) per Dapp?

Feedback welcomed!
![Payment Channel_ User flow UX Wireframes@2x  (4)](https://user-images.githubusercontent.com/597770/57888867-ec34f880-77f8-11e9-89dc-d10f61324328.png)

**Comment by omnat** [comment]
Nice! Added comments in Figma file!

After reading about payment channels. I have some more questions:
1. Looks like that if a tx happens between Alice and Bob via payment channel, they both gotta sign this tx. In the design we are so far considering "signing" when a transaction is outgoing because sender is confirming the tx with their account. Right? In recipient flow, should we think of a 'claiming' or 'accepting tx' action?
2. Payment channel wallet (QuickPay in Christian's design) is a child of an account, right? So does it have the same public address as its account?
3. Can it be detected to the user if a recipient's address is in the Hub (or have payment channel enabled)? - hence eligible for free/instant payments? 
4. There seems to be a transitive nature of transaction when multiple players are in a Hub. I read that if Alice and Bob both have a payment channel open with the same coffee shop, they can also transact with each other automatically. So if my understanding here is correct, is below how it'd work for transactions between 2 Metamask users, and a user & dApp(s)? 
<img width="1065" alt="Screen Shot 2019-05-17 at 5 11 40 PM" src="https://user-images.githubusercontent.com/44038140/57961926-469c8a80-78c7-11e9-92cd-8552ad5a593b.png">

- Alice's Account1 and Bob's Account1 have payment channels open with DApp XYZ (green lines)
Does this mean transaction between Alice and Bob's Account1 will be free/instant too? (yellow line)

- Even though DAppABC, Alice are in the same Hub, Alice can't interact with DAppABC for free because they don't have a payment channel open (red line). Correct? 

- If Alice's Account1 and Bob's Account2 have a payment channel open (green line), it doesn't mean Alice's Account 1 and Bob's Account 1 also have payment channel? Correct? 

Intuitively, I feel if Hub is just an accountant off-chain for all the parties who are entering this agreement/contract, it should be possible for a user to get in a contract that allows them to use the money they deposit in this payment channel, to be used for all dApps that are in the hub too. Can someone clarify if this is actually what's happening or am I missing something?

**Comment by omnat** [comment]
Sorry for bombarding if the above doesn't make any sense. Happy to chat live about them if that makes more sense...

**Comment by bdresser** [comment]
Lot of good questions in there Omna - maybe worth chatting live with @brunobar79 

Just adding that from our convo in standup today, it sounds like it will be technically challenging for dapps to open state channels, so the main usecases are p2p

**Comment by omnat** [comment]
Clarified in convo with Bruno & Christian, we are all on same page for now. Following capturing our chat today

- user can withdraw anytime, it costs gas which is deducted from their balance (behind the scenes)
- user can withdraw a % of their $ in payment channel
- there are limits to how much can be deposited - approx $8-$30 (limit is in ETH, so $ amount might fluctuate..)
- receipt from receiver technically happens, it'd be good practice to hide this away and receive automatically
- the diagram is accurate: payment channel per account (same public address), and by default there's a corresponding payment channel for each account
- as long as all players (wallets) are in same Hub (or different Hubs communicate with each other), a payment channel tx is possible within the limit
- tx between user & dApp not possible as dApp is typically a smart contract (on-chain), while payment channel by definition is off-chain. 

The use-cases that are possible from what we know now are p2p.

- Venmo (interpersonal global payments / settlements)
- p2p in dApp context (marketplace, exchange between players in a multi-player game)
- micro-tipping on a platform like Ujo or a web2 platform like Soundcloud (condition that they support our API, have ETH addresses of the content creators to allow fans to send $$)

**Comment by omnat** [comment]
From design sprint sync:

- Need to update prototype per feedback

**Comment by cjeria** [comment]
Updated payment channel designs here https://www.figma.com/proto/K1a0m5VRohRZV6EcpNzL6qxr/Payment-Channels?node-id=130%3A61&viewport=1703%2C-1359%2C0.4433267414569855&scaling=scale-down

Changes made:
- Removed the tutorial for this version, may need to create a new issue for that work + illustrations
- Attempting to keep transaction history UI as consistent as possible, using action icons instead of address identicons
- Reusing UI components from the classic send ETH flow for the deposit and send flows here
- Added the typical confirm screen for depositing into the payment channel

Open questions:
- should we keep the link to "instapay" in the top level nav drawer or put it inside the token list view as an "DAI Instapay" or something similar?
- Do we need mockups for the withdraw flow, or is it as simple as using a confirm screen?

Feedback welcome!

<a href="http://g.recordit.co/cxKFYRXi4I.gif" target="_blank"><img src="http://g.recordit.co/cxKFYRXi4I.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by cjeria** [comment]
cc @brunobar79 @estebanmino

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/60201057-ac542e80-9804-11e9-90c8-1c826f9e6653.png)

**Comment by bdresser** [comment]
"This is an experimental Layer 2 feature to let you send assets to friends without transaction fees. Made possible by Connext Payment Channels"

**Comment by omnat** [comment]
Note from user testing..

- Sharp eye of a user noticed we showcase tx history oldest -> latest in InstaPay. 
<img width="336" alt="Screen Shot 2019-06-27 at 1 35 29 PM" src="https://user-images.githubusercontent.com/44038140/60299077-b186ab80-98e0-11e9-972a-9bd47dfa2b61.png">
This isn't consistent with what they are used to in tx history latest -> oldest..
@cjeria should we keep InstaPay history consistent with tx history (latest -> oldest)?

**Comment by cjeria** [comment]
> This isn't consistent with what they are used to in tx history latest -> oldest.. @cjeria should we keep InstaPay history consistent with tx history (latest -> oldest)?

Whoa, not sure how I missed that one! good catch @omnat! Definitely should be reverse chronological order like we currently do everywhere.

**Comment by cjeria** [comment]
Also, I think @estebanmino brought this up earlier - the reason I used a deposit icon was that it's an incoming tx from the same account so instead of showing the same account's identicon, i went with an icon instead. 

For all other send tx's, we could revert to showing the identicon for the recipient account (until we revamp transaction UI).

**Comment by estebanmino** [comment]
> Also, I think @estebanmino brought this up earlier - the reason I used a deposit icon was that it's an incoming tx from the same account so instead of showing the same account's identicon, i went with an icon instead.

@cjeria a deposit is a tx sent to the smart contract not the address itself, so should we continue showing identicon of the sc ?

In that case should we remove that deposit icon ? I have this working now

![LbVEzbxx5l](https://user-images.githubusercontent.com/12115171/60458153-d8f4b580-9c0b-11e9-8b33-42b3745ad754.gif)

In addition, since deposits are on chain transactions we're showing it on the txs view so should we go with `Instant payment deposit` action key as the GIF ? Instead of `deposit` alone, maybe other message?

**Comment by cjeria** [comment]
Nice progress here @estebanmino. 

Looking at your GIF, You've made the top section fixed, however, I think we should make the whole page scroll the same way it does in all other views of the wallet.

> @cjeria a deposit is a tx sent to the smart contract not the address itself, so should we continue showing identicon of the sc ?

I think we should abstract away the concept of your ETH going to a smart contract on the surface layer. When I send money in a payment app to someone, I don't need to know the exact mechanism by which it gets to the receiver. I just care about it getting there. Same thing here. Since I'm transferring ETH from a regular account to a "special" account (payment channel) that I can see and control in my wallet, I think we should keep it straight forward by making it appear like you're just transferring between two of your accounts. Pushing the concept that ETH is going to a smart contract is more confusing than the former.

Also, if a user wants to dig deeper into viewing the details of their transaction ie. look at the smart contract details, we can show those details by expanding the transaction details (secondary layer details).

I also think the deposit icon is nice to distinguish between all other tx types in a quick scan of the tx history list.

@omnat  @bdresser, thoughts?

**Comment by estebanmino** [comment]
makes sense, so we have `Deposit` and `Withdraw` transactions that should be with these different icons, for txs between accounts we use identicons right?

![PRQQNvnUGf](https://user-images.githubusercontent.com/12115171/60540726-cea2ec00-9cdd-11e9-9b9e-5d0d3893bd9a.gif)

**Comment by cjeria** [comment]
@estebanmino Yep! I updated the prototype to represent the deposit, send and withdraw transactions. I also added the withdraw flow to the prototype. Let me know if there are more q's!

https://www.figma.com/proto/K1a0m5VRohRZV6EcpNzL6qxr/Payment-Channels?node-id=130%3A61&viewport=1703%2C-1359%2C0.4433267414569855&scaling=scale-down

**Comment by cjeria** [comment]
As a lo-fi way to improve the withdraw UX, can we add a system alert if the user taps on the withdraw button? Right now, if I accidentally tap on "withdraw", the action is executed and it feels like there should be a confirm alert with some more context. @estebanmino wdyt?

![image](https://user-images.githubusercontent.com/597770/60733310-b31c2900-9f09-11e9-84c9-99073399de25.png)

**Comment by estebanmino** [comment]
@cjeria yeah totally I already implemented something like that 

![image](https://user-images.githubusercontent.com/12115171/60733775-db148800-9f1b-11e9-86c4-745ec8a3d846.png)

Any update on the `instapay` logo ?  for the drawer view

**Comment by cjeria** [comment]
Nice! here's a custom-made instapay logo I forgot to upload!
https://www.dropbox.com/s/lyrvf9k74aeah51/mm-instapay.svg?dl=0

![image](https://user-images.githubusercontent.com/597770/60734948-e319fb00-9f0e-11e9-92ec-715cc2b0ed69.png)

**Comment by omnat** [comment]
Esteban built it out. 
This is up for Design QA in Sprint 16.
